[msg boots_000]
[s]リザーブ[n][e]

[msg boots_001]
[s]Solidly made[n]work boots.[n][e]

[msg boots_002]
[s]An ordinary pair of[n]loafers.[n][e]

[msg boots_003]
[s]Long, black boots.[n][e]

[msg boots_004]
[s]Boots with a horizontal[n]line over the toes.[n][e]

[msg boots_005]
[s]Classic-model sneakers.[n][e]

[msg boots_006]
[s]Shoes for playing[n]indoor soccer.[n][e]

[msg boots_007]
[s]Low-heeled boots.[n][e]

[msg boots_008]
[s]Sandals that massage[n]your pressure points.[n][e]

[msg boots_009]
[s]Strong enough to take[n]any punishment.[n][e]

[msg boots_00A]
[s]Boots with thick soles.[n][e]

[msg boots_00B]
[s]Sandals with many[n]bumps.[n][e]

[msg boots_00C]
[s]Boots made out of[n]leather.[n][e]

[msg boots_00D]
[s]Shoes with a single[n]row of wheels.[n][e]

[msg boots_00E]
[s]Geta made with the[n]latest technology.[n][e]

[msg boots_00F]
[s]Boots from military[n]surplus.[n][e]

[msg boots_010]
[s]Greaves colored[n]a dark red.[n][e]

[msg boots_011]
[s]Sandals that boost[n]the wearer's magic.[n][e]

[msg boots_012]
[s]Shoes made with[n]modern technology.[n][e]

[msg boots_013]
[s]Sandals worn by[n]ninjas.[n][e]

[msg boots_014]
[s]Shoes with needles[n]on the soles.[n][e]

[msg boots_015]
[s]Boots with jet engines[n]attached.[n][e]

[msg boots_016]
[s]Exceptionally durable[n]greaves.[n][e]

[msg boots_017]
[s]Very light shoes.[n][e]

[msg boots_018]
[s]Sandals with dazzling[n]silver ornaments.[n][e]

[msg boots_019]
[s]0x019[n][e]

[msg boots_01A]
[s]0x01A[n][e]

[msg boots_01B]
[s]Shoes with pentacle[n]symbols.[n][e]

[msg boots_01C]
[s]Hitmen's favorite[n]shoes.[n][e]

[msg boots_01D]
[s]Unbelievably light[n]pair of sandals.[n][e]

[msg boots_01E]
[s]A war god's spirit[n]dwells in these boots.[n][e]

[msg boots_01F]
[s]Boots that have been[n]blessed.[n][e]

[msg boots_020]
[s]Women's boots that[n]lend beauty.[n][e]

[msg boots_021]
[s]A famous ninja's[n]sandals.[n][e]

[msg boots_022]
[s]0x022[n][e]

[msg boots_023]
[s]0x022[n][e]

[msg boots_024]
[s]Men's boots embroidered[n]with dragons.[n][e]

[msg boots_025]
[s]Can supposedly be[n]remote-controlled...[n][e]

[msg boots_026]
[s]0x026[n][e]

[msg boots_027]
[s]A manly pair of[n]geta, for men.[n][e]

[msg boots_028]
[s]Shoes with vicious-[n]looking spikes.[n][e]

[msg boots_029]
[s]0x029[n][e]

[msg boots_02A]
[s]Sandals with a lion[n]drawn on them.[n][e]

[msg boots_02B]
[s]Men's greaves, worn[n]by a veteran warrior.[n][e]

[msg boots_02C]
[s]0x02C[n][e]

[msg boots_02D]
[s]0x02D[n][e]

[msg boots_02E]
[s]Sandals with a fresh[n]grass scent.[n][e]

[msg boots_02F]
[s]0x02F[n][e]

[msg boots_030]
[s]0x030[n][e]

[msg boots_031]
[s]0x031[n][e]

[msg boots_032]
[s]Savior's boots worn[n]only by men.[n][e]

[msg boots_033]
[s]0x033[n][e]

[msg boots_034]
[s]Leopard-print leggings[n]for women.[n][e]

[msg boots_035]
[s]0x035[n][e]

[msg boots_036]
[s]Lightweight pumps[n]for women.[n][e]

[msg boots_037]
[s]0x037[n][e]

[msg boots_038]
[s]Heels that make women[n]supersexy.[n][e]

[msg boots_039]
[s]0x039[n][e]

[msg boots_03A]
[s]0x03A[n][e]

[msg boots_03B]
[s]0x03B[n][e]

[msg boots_03C]
[s]Women's boots that[n]last forever.[n][e]

[msg boots_03D]
[s]The paw pads are very[n]soft to the touch.[n][e]

[msg boots_03E]
[s]0x03E[n][e]

[msg boots_03F]
[s]0x03F[n][e]

[msg boots_040]
[s]0x040[n][e]

[msg boots_041]
[s]0x041[n][e]

[msg boots_042]
[s]0x042[n][e]

[msg boots_043]
[s]0x043[n][e]

[msg boots_044]
[s]0x044[n][e]

[msg boots_045]
[s]0x045[n][e]

[msg boots_046]
[s]0x046[n][e]

[msg boots_047]
[s]Ordinary leg parts for[n]Aigis.[n][e]

[msg boots_048]
[s]Leg parts for Aigis made[n]with strong fibers.[n][e]

[msg boots_049]
[s]Processed iron leg parts[n]for Aigis.[n][e]

[msg boots_04A]
[s]Molecularly cohesive leg[n]parts for Aigis.[n][e]

[msg boots_04B]
[s]Ceramic leg parts for[n]Aigis.[n][e]

[msg boots_04C]
[s]Cobalt leg parts for[n]Aigis.[n][e]

[msg boots_04D]
[s]Lightweight leg parts for[n]Aigis.[n][e]

[msg boots_04E]
[s]Alloyed leg parts for[n]Aigis.[n][e]

[msg boots_04F]
[s]Consolidated leg parts[n]for Aigis.[n][e]

[msg boots_050]
[s]Leg parts for Aigis from[n]the Beast God.[n][e]

[msg boots_051]
[s]Black loafers.[n][e]

[msg boots_052]
[s]2052[n][e]

[msg boots_053]
[s]Shining leg parts for[n]Metis.[n][e]

[msg boots_054]
[s]Leather-covered leg parts[n]for Metis.[n][e]

[msg boots_055]
[s]Resin leg parts for Metis.[n][e]

[msg boots_056]
[s]Light ceramic leg parts[n]for Metis.[n][e]

[msg boots_057]
[s]Light alloy leg parts for[n]Metis.[n][e]

[msg boots_058]
[s]Titanium leg parts for[n]Metis.[n][e]

[msg boots_059]
[s]Zirconium leg parts for[n]Metis.[n][e]

[msg boots_05A]
[s]Imitation dancing shoes[n]for Metis.[n][e]

[msg boots_05B]
[s]Magical leg parts for[n]Metis.[n][e]

[msg boots_05C]
[s]Crimson leg parts for[n]Metis.[n][e]

[msg boots_05D]
[s]Angelic leg parts for[n]Aigis.[n][e]

[msg boots_05E]
[s]Mysterious glass leg[n]parts for Metis.[n][e]

[msg boots_05F]
[s]The ultimate prototype[n]leg parts for Aigis.[n][e]

[msg boots_060]
[s]Supreme pitch-black leg[n]parts for Metis.[n][e]

[msg boots_061]
[s]Comfortable leather shoes.[n][e]

[msg boots_062]
[s]0x062[n][e]

[msg boots_063]
[s]0x063[n][e]

[msg boots_064]
[s]0x064[n][e]

[msg boots_065]
[s]0x065[n][e]

[msg boots_066]
[s]0x066[n][e]

[msg boots_067]
[s]0x067[n][e]

[msg boots_068]
[s]0x068[n][e]

[msg boots_069]
[s]0x069[n][e]

[msg boots_06A]
[s]0x06A[n][e]

[msg boots_06B]
[s]0x06B[n][e]

[msg boots_06C]
[s]0x06C[n][e]

[msg boots_06D]
[s]0x06D[n][e]

[msg boots_06E]
[s]0x06E[n][e]

[msg boots_06F]
[s]0x06F[n][e]

[msg boots_070]
[s]0x070[n][e]

[msg boots_071]
[s]0x071[n][e]

[msg boots_072]
[s]0x072[n][e]

[msg boots_073]
[s]0x073[n][e]

[msg boots_074]
[s]0x074[n][e]

[msg boots_075]
[s]0x075[n][e]

[msg boots_076]
[s]0x076[n][e]

[msg boots_077]
[s]0x077[n][e]

[msg boots_078]
[s]0x078[n][e]

[msg boots_079]
[s]0x079[n][e]

[msg boots_07A]
[s]0x07A[n][e]

[msg boots_07B]
[s]0x07B[n][e]

[msg boots_07C]
[s]0x07C[n][e]

[msg boots_07D]
[s]Uniform for [f 4 2].[n][e]

[msg boots_07E]
[s]Uniform for [f 4 2][n]without the SEES band.[n][e]

[msg boots_07F]
[s]Summer uniform for [f 4 2].[n][e]

[msg boots_080]
[s]Winter uniform for [f 4 2].[n][e]

[msg boots_081]
[s]A traditional Japanese[n]shirt for men.[n][e]

[msg boots_082]
[s]A bathing suit for [f 4 2].[n][e]

[msg boots_083]
[s]Uniform for Yukari.[n][e]

[msg boots_084]
[s]Summer uniform for Yukari.[n][e]

[msg boots_085]
[s]Winter uniform for Yukari.[n][e]

[msg boots_086]
[s]A bathing suit for Yukari.[n][e]

[msg boots_087]
[s]Maid outfit for Yukari.[n][e]

[msg boots_088]
[s]Armor that looks like a bikini.[n][e]

[msg boots_089]
[s]Santa outfit for Yukari.[n][e]

[msg boots_08A]
[s]Aigis Default[n][e]

[msg boots_08B]
[s]Uniform for Aigis.[n][e]

[msg boots_08C]
[s]A one-piece dress for Aigis.[n][e]

[msg boots_08D]
[s]Maid outfit for Aigis.[n][e]

[msg boots_08E]
[s]Santa outfit for Aigis.[n][e]

[msg boots_08F]
[s]Uniform for Mitsuru.[n][e]

[msg boots_090]
[s]Summer uniform for Mitsuru.[n][e]

[msg boots_091]
[s]Winter uniform for Mitsuru.[n][e]

[msg boots_092]
[s]A bathing suit for Mitsuru.[n][e]

[msg boots_093]
[s]Maid outfit for Mitsuru.[n][e]

[msg boots_094]
[s]Armor that looks like a bikini.[n][e]

[msg boots_095]
[s]Santa outfit for Mitsuru.[n][e]

[msg boots_096]
[s]Uniform for Junpei.[n][e]

[msg boots_097]
[s]Summer uniform for Junpei.[n][e]

[msg boots_098]
[s]Winter uniform for Junpei.[n][e]

[msg boots_099]
[s]A bathing suit for Junpei.[n][e]

[msg boots_09A]
[s]Butler outfit for Junpei.[n][e]

[msg boots_09B]
[s]A traditional Japanese[n]shirt for men.[n][e]

[msg boots_09C]
[s]Uniform for Akihiko.[n][e]

[msg boots_09D]
[s]Summer uniform for Akihiko.[n][e]

[msg boots_09E]
[s]Winter uniform for Akihiko.[n][e]

[msg boots_09F]
[s]A bathing suit for Akihiko.[n][e]

[msg boots_0A0]
[s]Butler outfit for Akihiko.[n][e]

[msg boots_0A1]
[s]A traditional Japanese[n]shirt for men.[n][e]

[msg boots_0A2]
[s]Uniform for Ken.[n][e]

[msg boots_0A3]
[s]Summer uniform for Ken.[n][e]

[msg boots_0A4]
[s]Winter uniform for Ken.[n][e]

[msg boots_0A5]
[s]A bathing suit for Ken.[n][e]

[msg boots_0A6]
[s]Butler outfit for Ken.[n][e]

[msg boots_0A7]
[s]A traditional Japanese[n]shirt for men.[n][e]

[msg boots_0A8]
[s]Uniform for Shinjiro.[n][e]

[msg boots_0A9]
[s]Butler outfit for Shinjiro.[n][e]

[msg boots_0AA]
[s]A traditional Japanese[n]shirt for men.[n][e]

[msg boots_0AB]
[s]Koromaru default.[n][e]

[msg boots_0AC]
[s]Butler outfit for Koromaru...?[n][e]

[msg boots_0AD]
[s]Uniform for [f 4 2].[n][e]

[msg boots_0AE]
[s]Summer uniform for [f 4 2].[n][e]

[msg boots_0AF]
[s]Winter uniform for [f 4 2].[n][e]

[msg boots_0B0]
[s]Winter uniform for [f 4 2][n]without the SEES band.[n][e]

[msg boots_0B1]
[s]A bathing suit for [f 4 2].[n][e]

[msg boots_0B2]
[s]Maid outfit for [f 4 2].[n][e]

[msg boots_0B3]
[s]Armor that looks like a bikini.[n][e]

[msg boots_0B4]
[s]Santa outfit for [f 4 2].[n][e]

[msg boots_0B5]
[s]0x0B5[n][e]

[msg boots_0B6]
[s]0x0B6[n][e]

[msg boots_0B7]
[s]0x0B7[n][e]

[msg boots_0B8]
[s]0x0B8[n][e]

[msg boots_0B9]
[s]0x0B9[n][e]

[msg boots_0BA]
[s]0x0BA[n][e]

[msg boots_0BB]
[s]0x0BB[n][e]

[msg boots_0BC]
[s]0x0BC[n][e]

[msg boots_0BD]
[s]0x0BD[n][e]

[msg boots_0BE]
[s]0x0BE[n][e]

[msg boots_0BF]
[s]0x0BF[n][e]

[msg boots_0C0]
[s]0x0C0[n][e]

[msg boots_0C1]
[s]0x0C1[n][e]

[msg boots_0C2]
[s]0x0C2[n][e]

[msg boots_0C3]
[s]0x0C3[n][e]

[msg boots_0C4]
[s]0x0C4[n][e]

[msg boots_0C5]
[s]0x0C5[n][e]

[msg boots_0C6]
[s]0x0C6[n][e]

[msg boots_0C7]
[s]0x0C7[n][e]

[msg boots_0C8]
[s]0x0C8[n][e]

[msg boots_0C9]
[s]0x0C9[n][e]

[msg boots_0CA]
[s]0x0CA[n][e]

[msg boots_0CB]
[s]0x0CB[n][e]

[msg boots_0CC]
[s]0x0CC[n][e]

[msg boots_0CD]
[s]0x0CD[n][e]

[msg boots_0CE]
[s]0x0CE[n][e]

[msg boots_0CF]
[s]0x0CF[n][e]

[msg boots_0D0]
[s]0x0D0[n][e]

[msg boots_0D1]
[s]0x0D1[n][e]

[msg boots_0D2]
[s]0x0D2[n][e]

[msg boots_0D3]
[s]0x0D3[n][e]

[msg boots_0D4]
[s]0x0D4[n][e]

[msg boots_0D5]
[s]0x0D5[n][e]

[msg boots_0D6]
[s]0x0D6[n][e]

[msg boots_0D7]
[s]0x0D7[n][e]

[msg boots_0D8]
[s]0x0D8[n][e]

[msg boots_0D9]
[s]0x0D9[n][e]

[msg boots_0DA]
[s]0x0DA[n][e]

[msg boots_0DB]
[s]0x0DB[n][e]

[msg boots_0DC]
[s]0x0DC[n][e]

[msg boots_0DD]
[s]0x0DD[n][e]

[msg boots_0DE]
[s]0x0DE[n][e]

[msg boots_0DF]
[s]0x0DF[n][e]

[msg boots_0E0]
[s]0x0E0[n][e]

[msg boots_0E1]
[s]0x0E1[n][e]

[msg boots_0E2]
[s]0x0E2[n][e]

[msg boots_0E3]
[s]0x0E3[n][e]

[msg boots_0E4]
[s]0x0E4[n][e]

[msg boots_0E5]
[s]0x0E5[n][e]

[msg boots_0E6]
[s]0x0E6[n][e]

[msg boots_0E7]
[s]0x0E7[n][e]

[msg boots_0E8]
[s]0x0E8[n][e]

[msg boots_0E9]
[s]0x0E9[n][e]

[msg boots_0EA]
[s]0x0EA[n][e]

[msg boots_0EB]
[s]0x0EB[n][e]

[msg boots_0EC]
[s]0x0EC[n][e]

[msg boots_0ED]
[s]0x0ED[n][e]

[msg boots_0EE]
[s]0x0EE[n][e]

[msg boots_0EF]
[s]0x0EF[n][e]

[msg boots_0F0]
[s]0x0F0[n][e]

[msg boots_0F1]
[s]0x0F1[n][e]

[msg boots_0F2]
[s]0x0F2[n][e]

[msg boots_0F3]
[s]0x0F3[n][e]

[msg boots_0F4]
[s]0x0F4[n][e]

[msg boots_0F5]
[s]0x0F5[n][e]

[msg boots_0F6]
[s]0x0F6[n][e]

[msg boots_0F7]
[s]0x0F7[n][e]

[msg boots_0F8]
[s]0x0F8[n][e]

[msg boots_0F9]
[s]0x0F9[n][e]

[msg boots_0FA]
[s]0x0FA[n][e]

[msg boots_0FB]
[s]0x0FB[n][e]

[msg boots_0FC]
[s]0x0FC[n][e]

[msg boots_0FD]
[s]0x0FD[n][e]

[msg boots_0FE]
[s]0x0FE[n][e]

[msg boots_0FF]
[s]0x0FF[n][e]

